### ISSUE TITLE
Could not find module 'nativescript-couchbase'

### ISSUE THREAD

**Issue by tonyhogben** [triniwiz/nativescript-couchbase-plugin#16]
### Which platform(s) does your issue occur on?
- iOS and Android 
- iOS 12.1 and Android 4.4.4
- emulators and real devices (iPhone 6s and Nexus 4)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.1.1
- Cross-platform modules: 5.2.2
- Runtime(s): 5.1.1 and 5.1.0 (ios/android)
- Plugin(s): 
  "dependencies": {
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-couchbase-plugin": "^0.9.0",
    "nativescript-image-cache": "^1.0.6",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-plugin-firebase": "^4.0.5",
    "nativescript-telerik-ui": "^3.0.0-2017.6.22.5",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-timedatepicker": "^1.2.0",
    "tns-core-modules": "^5.2.2",
    "tns-core-modules-snapshot": "3.0.1-5.5.372.32"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.8.0",
    "tns-platform-declarations": "^3.1.0",
    "typescript": "~2.2.1"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
I have updated my project and upon discovering nativescript-couchbase has been abandoned, removed it and replaced with nativescript-couchbase-plugin.

### Is there any code involved?
The app will build and install on the device but then crashes with the message: 

`java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.co.wholeschoolmeals.app/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-couchbase", relative to: app/tns_modules/`

I have attempted to reset the app by removing the node_modules, hooks and platform folders and running 'npm i'.

Here is a zip of the project: [](https://mtstudios.digitalpigeon.com/msg/GrVr4EDgEemx8gYtQsGbAw/CLWo8uaZoCWCeo7JBz-bDA/file/2942dad0-40e0-11e9-85e8-06e26140e7ff/download# - Whole-School-Meals-v2.zip - Whole-School-Meals-v2.zip)

Thanks in advance,

Tony.

**Comment by triniwiz** [comment]
you are using the wrong package name `nativescript-couchbase-plugin` is the correct name

**Comment by tonyhogben** [comment]
Sorry, maybe I didn't describe the issue correctly. If you see my dependencies, I am using `nativescript-couchbase-plugin` but my project is still trying to reference `nativescript-couchbase` even though I have removed that plugin and refreshed the project. 

I can't for the life of me work out why. If this is not an issue with either of these two plugins, maybe I will have to post in the main nativescript gihub issues.

#veryconfused

**Comment by Izrab** [comment]
@tonyhogben Delete ".platforms", ".cloud", and "node_modules" folders, and delete "package-lock.json" file, also click on "clean cloud workspace" in Sidekick GUI (if you use cloud builds).
Also recheck package.json to insure it is `nativescript-couchbase-plugin`, also when requiring or importing couchbase plugin module, follow the docs and samples.
