### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by ShyshkovOleg** [triniwiz/nativescript-couchbase-plugin#28]
Is there any way to chain WHERE in a query?
What does 'logical?' operator and 'between' do? 
What is offset property?

**Comment by ShyshkovOleg** [comment]
Hope it would save someone time. You could chain query results like this:
`const res = localDatabaseName.query({
            select: [],
            where: [
                { property: "time", comparison: "greaterThanOrEqualTo", value: start },
                { property: "time", comparison: "lessThanOrEqualTo", value: end }
            ]
        });`

**Comment by triniwiz** [comment]
The new docs are located [here](https://triniwiz.github.io/nativescript-plugins/api-reference/couchbase.html#couchbase) I'll try to add more info
