### ISSUE TITLE
QueryWhereItem - Case insensitive comparation

### ISSUE THREAD

**Issue by Pkurto** [triniwiz/nativescript-couchbase-plugin#30]
Hello,

I am using this plugin with my Nativescript application. 
I am filtering the Couchbase results by a productName property but I cannot find a way to do this filtering case-insensitive. For example:

`` this.database.query({
      select: [], 
      where: [{ property: 'productName', comparison: 'like', value: '%test%' }]
   });``

Is there a possible way to use like case-insensitive?
Using lower or upper conversions, how can I query like "lower(productName) LIKE %test%"?

Regards,
Pedro

**Comment by Pkurto** [comment]
Any idea?

I also tried to query with the "regex" operator without success:

`[{ property: 'productName', comparison: 'regex', 'test/gi'}]`

and`
[{ property: 'productName', comparison: 'regex', '/test/gi'}];`

**Comment by Pkurto** [comment]
I found a way to do the case-insensitive search but I do not recommend it. **It is not an acceptable answer** for this problem because the query will be very heavy. Can anyone help me to resolve this with a better solution?

` [{"property":"productName","comparison":"regex","value":"[tT][eE][sS][tT]"}]`

**Comment by triniwiz** [comment]
So it looks like the regex operator isn't using the correct native builder

**Comment by triniwiz** [comment]
Android right?

**Comment by Pkurto** [comment]
Yes it occurred in Android. I will test it on IOS tomorrow and give you the feedback.

**Comment by triniwiz** [comment]
Looks like iOS is handled like it should

**Comment by Pkurto** [comment]
I confirmed that for IOS is not working as well:
`[{ property: 'productName', comparison: 'regex', 'test/gi'}]` or
`[{ property: 'productName', comparison: 'regex', '/test/gi'}];`

If I remove the '/' and '/gi' from the above example it searches as 
`[{ property: 'productName', comparison: 'like ', '%test%'}];`

**Comment by Pkurto** [comment]
Any news on this problem?

**Comment by Pkurto** [comment]
Any update on this bug? or workaround?

**Comment by timostuebing** [comment]
Same here: It would be great to have the possibilty to query Couchbase case-insensitive here.

In our project, we implemented a product search where it would be really convenient for the user to not worry about capitalization of product names.

Any help appreciated.

**Comment by triniwiz** [comment]
can you try `like` 😄

**Comment by Pkurto** [comment]
like is not case insensitive.

**Comment by triniwiz** [comment]
feel free to reopen 😃

**Comment by Pkurto** [comment]
I notice that you share a new plugin release. 
I removed the old couchbase plugin, clean the android platform and installed the new plugin version. However, I am getting the following error on compile:
`ERROR in node_modules/nativescript-couchbase-plugin/index.d.ts(36,47): error TS2304: Cannot find name 'CBLListenerToken'.`

Can you check this problem?

**Comment by triniwiz** [comment]
try upgrading again 😄

**Comment by Pkurto** [comment]
With your correction the code is compiling again. However, when I try to search a text with the like operator it close the app without any error on the logs :(

I'm using multiple properties in the where clause, for example:
`[{"property":"productName","comparison":"like","value":"%life%"},{"property":"etag","comparison":"like","value":"%life","logical":"or"},{"property":"tradeName","comparison":"like","value":"%life%","logical":"or"}`

I need your help because this behavior is worse than search with case-sensitive and crashes the app.

**Comment by OliverNiebsch** [comment]
Same here. I need a case-insensitive search with like, but with the version 0.9.4 or 0.9.5 the app crashes whenever I'm using a query with like or regex.

Crashes happens on iOS and Android. On Android I got this Exception:
`JNI ERROR (app bug): attempt to pass an instance of java.lang.String as argument 1 to com.couchbase.lite.Expression com.couchbase.lite.AbstractFunction.lower(com.couchbase.lite.Expression) `

Looking into the commit and some documentation of the couchbase plugins it seems that the functions `com.couchbase.lite.Function.lower` and `CBLQueryFunction.lower` expect an Expression but you put in the `item.property` as a String. My suggestion is you have to transform the property into an Expression and then using the lower function:
`CBLQueryFunction.lower(CBLQueryExpression.property(item.property)).like(...)`
`com.couchbase.lite.Function.lower(com.couchbase.lite.Expression.property(item.property).like(...)`

@triniwiz I hope this information are helpful for you to fix this bug 😄

**Comment by Pkurto** [comment]
@triniwiz can you check the @OliverNiebsch comment and see if it is possible to solve this issue?
App is crashing whenever we're using a "like" operator :(

**Comment by OliverNiebsch** [comment]
@Pkurto Can you please reopen this issue since it's not solved yet?

I'm also waiting and looking forward to this fix.

**Comment by Pkurto** [comment]
@OliverNiebsch I already try to re-open this issue, however I cannot see that option in git.
Maybe because I'm not a repo collaborator and @triniwiz close it?

@triniwiz can you re-open this issue?

**Comment by Pkurto** [comment]
any update on this issue?

**Comment by triniwiz** [comment]
@Pkurto updating some plugins so I'll try to fit it in

**Comment by Pkurto** [comment]
@triniwiz thank you, I will wait for an update :)

**Comment by timostuebing** [comment]
@triniwiz I hope you had a good New Year!
Is there a chance that you find the time to look into this and build a new release? Would really appreciate it!

**Comment by triniwiz** [comment]
fixed: https://github.com/triniwiz/nativescript-couchbase-plugin/commit/45adb494c43cab01d2d4b2a7cbd19c67b587314b
released: https://github.com/triniwiz/nativescript-couchbase-plugin/commit/79154fe8a0d2267ca7233e9eef85816b5dee8b0d

**Comment by Pkurto** [comment]
Happy new year @triniwiz.
I tried your new release and when we search in lowercase it works correctly and case insensitive:
> Search clause "like %car%": will match with all strings like "xCAR", "CAR", "CARx"

However, if you use uppercase in the search text it will not match with any string:
>  Search "like %CAR%" or '%Car%': do not return any result

Please, can you fix this bug? This feature has a big value for your application.
Waiting for updates, 
Best Regards

**Comment by Pkurto** [comment]
If I force all text insert by the user to lowercase before passing to QueryWhereItem it will work.
I think you are forcing lowercase in the information from the db property and forgot to lowercase the input comparison value.

Hope this help.
