### ISSUE TITLE
QUERY: WHERE

### ISSUE THREAD

**Issue by Marc-Cilliers** [triniwiz/nativescript-couchbase-plugin#41]
Is it possible to query a property's property? 
Following on from the example you created, if I have a user:

```javascript
{
    "firstname": "O",
    "lastname": "Fortune",
    "address": {
        "country": "Trinidad and Tobago"
    },
    "twitter": "https://www.twitter.com/triniwiz"
}
```

How do I query based on the country?

Is it:

```javascript
where: [{ property: 'address', comparison: 'equalTo', value: 'country: "Trinidad and Tobago"' }],
```

Or is it:

```javascript
where: [{ property: 'address.country', comparison: 'equalTo', value: 'Trinidad and Tobago' }],
``` 
?

**Comment by gnubyte** [comment]
Open a thread on stackoverflow and post it back here and I'll answer both this one and the stackoverflow post. I need the stackoverflow credit, lol.

Cheers.

**Comment by cvietor** [comment]
a little late to the party, but for future reference:

it is the second one:
`where: [{ property: 'address.country', comparison: 'equalTo', value: 'Trinidad and Tobago' }],`
