### ISSUE TITLE
Storage of App on devices increase even deleting data

### ISSUE THREAD

**Issue by tingfong214** [triniwiz/nativescript-couchbase-plugin#42]
I am using this plugin with my Nativescript application.
This app is heavily using this plugin creating, updating, deleting, querying local databases.
It's okay the storage on device increases when new data is created
However, the storage increased even when data is updated or even deleted. 
Hence, the storage of this app on devices is increasing in a very short period.

![86806621_789573164866048_6106938123290148864_n](https://user-images.githubusercontent.com/26363028/74623257-e0f36c80-517e-11ea-8221-e12db4bbbbb9.jpg)

The data size has been increased to a few hundred MB

Is anyone facing this problem too?

**Comment by drewjbartlett** [comment]
I've noticed that `.destroyDatabase` doesn't do anything. I've had to write my own method that iteratively deletes every record which is not ideal.

**Comment by triniwiz** [comment]
Can you try the [latest version](https://github.com/triniwiz/nativescript-plugins) for v7 since it's using their latest sdk
