### ISSUE TITLE
Support for CBL 2.7

### ISSUE THREAD

**Issue by rayneram** [triniwiz/nativescript-couchbase-plugin#43]
Is it possible to update this plugin to support Couchbase Lite v2.7? There have been a number of key fixes since the currently supported release (2.5.3).

**Comment by triniwiz** [comment]
Thanks I’ll look

**Comment by drewjbartlett** [comment]
@triniwiz I am using this library heavily in my app. Are there things I can help you with to improve this? I'm happy to lend a hand.

**Comment by ghinazi** [comment]
any updates on this?

**Comment by triniwiz** [comment]
Updated to 2.8.x [here](https://github.com/triniwiz/nativescript-plugins)
