### ISSUE TITLE
Couchbase Lite Exception -> Can't delete db file while other connections are open

### ISSUE THREAD

**Issue by lostation** [triniwiz/nativescript-couchbase-plugin#46]
Hi Triniwiz,

First of all ... as always thank you for all you've done for NS !

Then... I'm facing maybe dumb issue...

I'm trying to delete|destroy database content... So I'm calling myDB.destroyDatabase();
Strangely if myDB has already been opened and fulfilled with some data and then I want to destroy data, I get this exception. 

--> CouchbaseLiteException{domain='CouchbaseLite', code=16, msg=Can't delete db file while other connections are open}

Then how can I close properly (or force to close) myDB before create new one ? 
Or maybe I need to loop over my existing documents to delete them separately ?

Thanks in advance.
Lo.

**Comment by triniwiz** [comment]
I didn’t expose a close method but you can try `myDB.android || .ios.close()` <- which ever platform you’re on

**Comment by lostation** [comment]
Yep that seems to do the trick ;) Thanks.
Now I'm getting the database, do my stuffs and right after I close it. I'm not sure it's a performance issue...to close every time...but it seems to work.

But do you have an idea how to create index from your plugin ? 
I have to manage about 3000 items and it not seems very fast when I do query all the items is about 3 sec...

**Comment by triniwiz** [comment]
I did not expose that feature but will add it in the next version also it would be v7 only another I can try enabling the multithreaded feature (currently begin a flag v7 only) then you even use the batch method 🙂

**Comment by lostation** [comment]
Aïe I'm not quite ready to upgrade to NS7 right now... I'm working on a big entreprise angular shared project...so it's a huge truck to move ;)
Thanks Osei.

**Comment by triniwiz** [comment]
Ah understood , you see I’m doing a massive clean up with all the plugins I maintain an the ones that got under-maintained ... I think everyone would love the next move 🙂

**Comment by lostation** [comment]
sure !

**Comment by lostation** [comment]
Finally... I will wait until your next plugin version, currently Couchbase is way too slow for my needs... Or maybe it's not the right tool. I don't know... I've simply compared its read performance with a simple string application storage done by child workers and that's really really more performant...From 3 sec to some milliseconds...Unbelievable, I've even added a timeout to let the time for some UI things to happen...More luck on next try. Cheers.
