### ISSUE TITLE
createView is not a function

### ISSUE THREAD

**Issue by mauriciopena** [triniwiz/nativescript-couchbase-plugin#47]
Hello,

when I try to create a view like this:

import { Couchbase } from 'nativescript-couchbase-plugin'

const db = new Couchbase('my-db')

db.createView("myview", "1", function(document, emitter) {
  emitter.emit(document._id, document) 
})

I'm getting "createView is not a function". How can I create a view with this plugin?

**Comment by triniwiz** [comment]
in v2.0 they removed it I think for in favour of queries
